// domain/entities/Well.ts
export class Well {
  constructor(
    public itemName: string,
    public campo: string,
    public product: string,
    public status: string,
    public x: number,
    public y: number,
    public plataforma: string,
    public joblogStartDate: Date,
    public engJoblogStartDate: Date,
    public joblogEndDate: Date,
    public engJoblogEndDate: Date,
    public joblogType: string,
    public joblogWoNumber: number,
    public joblogActivity: string,
    public joblogWoEquip: string,
    public longWellName: string,
    public minId: string,
    public chActivity: string,
    public chRig: string,
    public joblogStartSuspen: Date,
    public joblogEndSuspen: Date,
    public commentsDrilling: string,
    public joblogStartRigMov: Date,
    public joblogEndRigMov: Date,
    public nextWellMov: string,
    public targetWellMov: string,
    public rigStarttime: Date,
    public rigEndtime: Date,
    public rig: string,
    public rigDestiny: string,
    public rigActivity: string,
    public rigObs: string,
    public xDestiny: number,
    public yDestiny: number,
  ) {}
}
